import { html } from '../html.js';
import { site } from '../site.js';
import { facts } from '../components.js';

const TOOLS = [
  ['Every day', 'Python, Django, PostgreSQL, JavaScript, HTML and CSS, Git'],
  ['Often', 'Django REST Framework, Celery, Redis, Tailwind CSS, Alpine.js, ReportLab'],
  ['Mobile and desktop', 'Kotlin, Jetpack Compose, CameraX, ML Kit, Room, Swift for small native wrappers'],
  ['Shipping', 'Heroku, GitHub Actions, Amazon S3'],
];

export function about() {
  return {
    path: '/about/',
    section: 'about',
    title: `About — ${site.name}`,
    description: `About ${site.name}: a first-year engineering student at ${site.school} from El Jadida, Morocco, who builds software for schools and small businesses.`,
    body: html`
      <div class="about wrap">
        <header class="about-head">
          <h1>About</h1>
        </header>

        <section class="section" aria-label="Story">
          <picture class="portrait">
            <img src="/images/yasser-mansour.webp" width="408" height="612" alt="Portrait of Yasser Mansour in a dark suit and tie." decoding="async">
          </picture>
          <div class="prose">
            <p class="lead">I’m Yasser. I’m from El Jadida, Morocco, and I’m in my first year at ${site.school}, the engineering school. I wrote my first code at 13 and taught myself the rest by building things.</p>
            <p>Most of what I build starts from a concrete problem. Parents should hear about an absence the same day, not at the end of the term. A small organisation’s monthly accounts shouldn’t need a calculator. A shop’s till should be able to scan barcodes with a phone and print a receipt without a dialog box. I design the data model, write the backend and the interface, deploy it, and keep it running once people depend on it. A lot of it is built on request for people and organisations, and stays private.</p>
            <p>A few things I now treat as rules. Money is stored as <code>Decimal</code>. A report someone printed last month must not quietly change. A phone on a bad connection will send the same request twice, so the server had better not act on it twice. Where I can, rules like these become tests.</p>
            <p>I work mostly in Python and Django, with PostgreSQL, and reach for Kotlin when something needs to live on a phone. I speak ${site.languages.join(', ').replace(/, ([^,]*)$/, ' and $1')}.</p>
          </div>
        </section>

        <section class="section" aria-labelledby="now">
          <h2 id="now">Now</h2>
          <div class="prose">
            <p>First year at ${site.school}. Building <a href="/work/lifeos/">LifeOS</a>, which is in beta.</p>
          </div>
        </section>

        <section class="section" aria-labelledby="tools">
          <h2 id="tools">Tools</h2>
          ${facts(TOOLS, 'facts facts--stack')}
        </section>

        <section class="section" id="colophon" aria-labelledby="colophon-title">
          <h2 id="colophon-title">Colophon</h2>
          <div class="prose">
            <p>Designed and built by ${site.name}. The pages are plain HTML and CSS, generated by a short Node script from one file of project data. There is no framework, no client-side rendering and no analytics; the only JavaScript shows the local time and copies my email address.</p>
            <p>Set in IBM Plex Sans and IBM Plex Mono, served from this domain. Screenshots are of the real products: their public pages, or the apps running locally with sample data. <a href="${site.source}">Source on GitHub</a>.</p>
          </div>
        </section>
      </div>`,
  };
}
